# YEAR WISE TOTAL DEATH

SELECT YEARS,
SUM(
        ACUTE_HEPATITIS_DEATHS +
        MENINGITIS_DEATHS +
        DEMENTIA_DEATHS +
        PARKINSONS_DEATHS +
        MALARIA_DEATHS +
        DROWNING_DEATHS +
        HIV_AIDS_DEATHS +
        DRUGS_DEATHS +
        TUBERCULOSIS_DEATHS +
        CARDIOVASCULAR_DEATHS +
        RESPIRATORY_DEATHS +
        NEONATAL_DISORDER_DEATHS +
        ALCOHOL_DEATHS +
        DIARRHEAL_DEATHS +
        NEOPLASM_DEATHS +
        CONFLICT_DEATHS +
        DIABETES_DEATHS +
        KIDNEY_DEATHS +
        POISONING_DEATHS +
        ROAD_DEATHS +
        LIVER_DEATHS +
        DIGESTIVE_DISEASE_DEATHS +
        FIRE_DEATHS +
        MEAELES_DEATH
    ) AS total_deathsByYear
FROM DEATH_DATA GROUP BY YEARS ORDER BY YEARS ASC;